apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm-1
data:
  index.html: |
    <html>
    <head><title>Welcome Green Team</title></head>
    <body/>
    <h1>This is Deployment One</h1>
    </body></html>

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm-2
data:
  index.html: |
   <html>
    <head><title>Welcome Green Team</title></head>
    <body/>
    <h1>This is Deployment Two</h1>
    </body></html>>

---