apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm-1
data:
  index.html: |
    <html>
    <h1>Welcome Green Team</h1>
    </br>
    </html
    <h1>This is Deployment One</h1>
    </html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm-2
data:
  index.html: |
    <html>
    <h1>Welcome Green Team</h1>
    </br>
    </html
    <h1>This is Deployment Two</h1>
    </html