apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm-1
data:
  index.html: |
    <html>
    <head><title>Welcome Green Team</title></head>
    <body/>
    <h1>This is Deployment One</h1>
    </body></html>

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm-2
data:
  index.html: |
   <html>
    <head><title>Welcome Green Team</title></head>
    <body/>
    <h1>This is Deployment Two</h1>
    </body></html>

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: config-1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-1
        configMap: 
          name: nginx-cm-1

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: config-2
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-2
        configMap:
          name: nginx-cm-2
                
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: my-service
    port: 80

