apiVersion: apps/v1
kind: Deployment
metadata: 
  name: Deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
```
apiVersion: v1
kind: Service
metadata:
spec:
```
apiVersion:
kind: ConfigMap