Error

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: prod-deployment
  labels:
    env: production   
spec:
  replicas: 3
  selector:
    matchLabels:
      label: production   # replave with <env: production>
  template:
    metadata:
      labels:
        app: production   # replace with <env: production>
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

      

