apiVersion: v1
kind: Service
metadata:
  name: api-stable
spec:
  type: ClusterIP
  selector:
    app: api
    lifecycle: stable

  ports:
    - protocol: TCP
      port: 80 # Ensure port 80 is exposed for this service
      targetPort: 8080 # This is the container port, which runs on port 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      lifecycle: stable
  template:
    metadata:
      labels:
        app: api
        lifecycle: stable
    spec:
      containers:
      - name: api
        image: hashicorp/http-echo
        args:
          - -listen=:8080
          - -text={'runs_on':'kubernetes','lifecycle':'stable','api_version':'v1'}